server:
  address: localhost
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${DB_PASSWORD}
    url: jdbc:mysql://localhost:3306/${DB_URL}
    username: ${DB_USERNAME}
  ## JPA Setting Info
  jpa:
    hibernate:
      ddl-auto: create  # option type: create, create-drop, update, validate, none
    properties:
      hibernate:
        direct: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
      jakarta:
        persistence:
          persistence-unit-name: jpa-test
    generate-ddl: true
    show-sql: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace